Added EF core ORM with Postgres Db
den2201/CardsService pull request #2
Opened 2021-12-06 06:55 UTC by den2201

2021-12-10 23:22 UTC, IgorZudov requested changes

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/CardController.cs
> +                return await Task.FromResult(Ok(new ApiResponseModel<DBNull>{ IsOkStatus = true}));
await Task.FromResult выглядит избыточным, можно вернуть просто new ApiResponseModel<DBNull>{...

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/CardController.cs
> +                return await Task.FromResult<ActionResult>(Ok(new ApiResponseModel<DBNull> { IsOkStatus = true }));
Да, от Task,FromResult стоит избавиться

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/TransactionController.cs
> +    public class TransactionController : ControllerBase
Не хватает необходимых атрибутов

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/TransactionController.cs
> +        public async Task<ActionResult> CreateTransactionByNewCard([FromBody] TransactionNewCard transaction)
transaction можно вынести в роут контроллера

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/TransactionController.cs
> +        [HttpPost("transaction/add/cardId")]
add по сути избыточно, так как POST запроса достаточно

2021-12-10 23:22 UTC, IgorZudov commented on Controllers/TransactionController.cs
> +        public async Task<ActionResult> CreateTransactionAllCards([FromBody] Tuple<string, float> transactionData)
лучше не использовать Tuple. Создание конкретной модели никогда не будет лишним

2021-12-10 23:22 UTC, IgorZudov commented on Database/AppDbContext.cs
> +        public DbSet<CardDateExpired> CardDateExpired { get; set; }
форматирование немного поехало))

2021-12-10 23:22 UTC, IgorZudov commented on Database/AppDbContext.cs
> +            modelBuilder.Entity<Card>().HasData(
nit: инициализацию каких-то стартовых данных лучше реализовывать в отдельном классе или методе расширения

2021-12-10 23:22 UTC, IgorZudov commented on Domain/Card.cs
> +        public List<TransactionHistory> TransList { get; set; }
не стоит прибегать к сокращениям, когда описывается доменная модель

2021-12-10 23:22 UTC, IgorZudov commented on Migrations/20211208152044_Init.cs
> +                    CVC = table.Column<string>(type: "text", nullable: true),
для CVC и PAN лучше указать ограничения в размере полей

2021-12-10 23:22 UTC, IgorZudov commented on Migrations/20211208152044_Init.cs
> +                    CVC = table.Column<string>(type: "text", nullable: true),
Вообще можно всю схему пересмотреть на момент добавления ограничений

2021-12-10 23:22 UTC, IgorZudov commented on Startup.cs
> +            //                context.Response.ContentType = "application/json";
думаю, что это можно удалить, реализация мидлвар останется в истории

2021-12-13 06:05 UTC, den2201 commented on Controllers/CardController.cs
> +                return await Task.FromResult(Ok(new ApiResponseModel<DBNull>{ IsOkStatus = true}));
fixed

2021-12-13 06:05 UTC, den2201 commented on Controllers/CardController.cs
> +                return await Task.FromResult<ActionResult>(Ok(new ApiResponseModel<DBNull> { IsOkStatus = true }));
fixed

2021-12-13 06:10 UTC, den2201 commented on Controllers/TransactionController.cs
> +    public class TransactionController : ControllerBase
added

2021-12-13 06:10 UTC, den2201 commented on Controllers/TransactionController.cs
> +        [HttpPost("transaction/add/cardId")]
deleted

2021-12-13 06:11 UTC, den2201 commented on Database/AppDbContext.cs
> +        public DbSet<CardDateExpired> CardDateExpired { get; set; }
+

2021-12-13 06:33 UTC, den2201 commented on Database/AppDbContext.cs
> +            modelBuilder.Entity<Card>().HasData(
added dataseeder class

2021-12-13 06:35 UTC, den2201 commented on Domain/Card.cs
> +        public List<TransactionHistory> TransList { get; set; }
fixed

2021-12-13 06:49 UTC, den2201 commented on Migrations/20211208152044_Init.cs
> +                    CVC = table.Column<string>(type: "text", nullable: true),
added

2021-12-13 06:51 UTC, den2201 commented on Startup.cs
> +            //                context.Response.ContentType = "application/json";
done

2021-12-19 20:02 UTC, merged